### ISSUE TITLE
subsetByAssay(), subsetByRow(), subsetByColumn() still around

### ISSUE THREAD

**Issue by lwaldron** [vjcitn/MultiAssayExperiment#126]
Still defined in R/MultiAssayExperiment-methods.R, have man pages, and noted in MultiAssayExperiment show method, but are not exported.  Vignette uses e.g. subset(MAE, "columns") instead, which I think is now the recommended way along with `[`.

**Comment by LiNk-NY** [comment]
The subsetBy* functions are used by the `[` bracket method when subsetting a MultiAssayExperiment ([see here](https://github.com/vjcitn/MultiAssayExperiment/blob/master/R/MultiAssayExperiment-methods.R#L148)). They are documented because they are generics. I may be able to change them to what they intend using signatures such as `c("MultiAssayExperiment", "missing", "missing", "ANY")` in the case of `subsetByAssay` for a bracket `[` subset method.

**Comment by lwaldron** [comment]
What's confusing is that they are documented and also suggested in the MultiAssayExperiment show method, but are only available through triple colon `:::`. This seems not the norm to me, or have you seen other non-exported S4 generics documented?

**Comment by LiNk-NY** [comment]
We discussed removing ?`subset,MultiAssayExperiment-method` from the package and exporting subsetBy* functions
