### ISSUE TITLE
broken subset by columns for ov MAE

### ISSUE THREAD

**Issue by lwaldron** [vjcitn/MultiAssayExperiment#127]
For example:

```
> download.file("https://www.dropbox.com/s/kc6pa3xie9oiyxt/ovMAEO.Rda?dl=0", 
              destfile="ovMAEO.Rda", method="wget")
> load("ovMAEO.Rda")
> cn <- colnames(ovMAEO)
> ovMAEO[, cn[[1]][1:5], ]
Error in subsetByColumn(x, j) : No matching identifiers found
> subset(ovMAEO, cn[[1]][1:5], "columns")
Error in subsetByColumn(x = x, y = indicator) : 
  No matching identifiers found
```

Perhaps this is related to the column names being not valid R names (containing "-")?

```
> cn[[1]][1:5]
[1] "tcga-04-1348-01" "tcga-04-1357-01" "tcga-04-1362-01" "tcga-04-1364-01" "tcga-04-1365-01"
```

**Comment by LiNk-NY** [comment]
This might be due to non matching in rownames(pData(ovMAEO)) and the colnames(ovMAEO).

**Comment by lwaldron** [comment]
Oops, my mistake.  But how about this?

```
> pat <- rownames(pData(ovMAEO))
> ovMAEO[, pat[1:5], ]
Error in orig[[nm]][, j, ..., drop = drop] : subscript out of bounds
> ovMAEO[, 1:5, ]
Error in orig[[nm]][, j, ..., drop = drop] : subscript out of bounds
```

**Comment by LiNk-NY** [comment]
It doesn't seem like the data is there. I would have to check the original script for creating the miRNASeqGene ExpressionSet for OV. 
```
sum(colnames(ovMAEO)[[2]] %in% rownames(pData(ovMAEO))[1:5])
```

**Comment by lwaldron** [comment]
I don't see the output of the command you entered, but why should it return something other than zero?  colnames of the assays don't have to match rownames of pData, they're related by sampleMap. The object definitely has data:

```
> ovMAEO
A "MultiAssayExperiment" object of 8 listed
 experiments with user-defined names and respective classes. 
 Containing an "Elist" class object of length 8: 
 [1] RNASeq2GeneNorm: "ExpressionSet" - 20501 rows, 83 columns 
 [2] miRNASeqGene: "ExpressionSet" - 705 rows, 85 columns 
 [3] CNASNP: "RangedRaggedAssay" - 100673 rows, 167 columns 
 [4] CNVSNP: "RangedRaggedAssay" - 34146 rows, 167 columns 
 [5] CNACGH: "RangedRaggedAssay" - 44241 rows, 166 columns 
 [6] Methylation: "ExpressionSet" - 27578 rows, 85 columns 
 [7] mRNAArray: "ExpressionSet" - 18632 rows, 85 columns 
 [8] miRNAArray: "ExpressionSet" - 821 rows, 85 columns 
```

**Comment by LiNk-NY** [comment]
Sorry I meant to enter: 
```
sum(RTCGAToolbox::bcIDR(colnames(ovMAEO)[[2]]) %in% rownames(pData(ovMAEO))[1:5])
```

**Comment by lwaldron** [comment]
I'm not sure what you're showing, but sampleMap is working as it should, for example the 85 assays in miRNASeqGene map to 85 patients in pData:

```
> smrows <- match(colnames(ovMAEO)[[2]], sampleMap(ovMAEO)[, 2])
> sm.sub <- sampleMap(ovMAEO)[smrows, ]
> pData(ovMAEO)[sm.sub$primary, 1:2]
DataFrame with 85 rows and 2 columns
             years_to_birth vital_status
                <character>  <character>
tcga-04-1348             44            1
tcga-04-1357             52            0
tcga-04-1362             59            1
tcga-04-1364             61            1
tcga-04-1365             87            0
...                     ...          ...
tcga-25-1320             65            1
tcga-25-1321             65            1
tcga-25-1322             62            1
tcga-25-1323             72            1
tcga-25-1329             76            1
> 
```

**Comment by LiNk-NY** [comment]
`match` is not the right function to use because it will return the first matches that are present in the sampleMap. If you look at `sm.sub`, it contains results for the "RNASeq2GeneNorm" assay. 
To search within the assay, I suggest using `mapToList` such that you get the subset of IDs/sampleNames `mapToList(sampleMap(ovMAEO))["miRNASeqGene"][[1]]`. Either way, you should have the right identifiers. 

If you try to subset an ExpressionSet with invalid/non-matchable sample names you will get that same error. 

It could be that the IDs in the data are not matching what is in the `sampleMap`. 

I will add a validity check to ensure that the sample IDs in the sampleMap and in the Elist are equal.

**Comment by LiNk-NY** [comment]
There was an issue with the data so the sample names that were being looked for were not there in the MultiAssayExperiment object. 
The validity check [(1.iii.)](https://github.com/vjcitn/MultiAssayExperiment/wiki/MultiAssayExperiment-API#validity) has been modified e3f3c56 so that sorted sample names ("assay" column of the sampleMap) are identical to the sorted column names in each of the assays. 

For more detail, see the gist [here](https://gist.github.com/LiNk-NY/9012af887aa15c6a03ee635a7fc8a461).
