### ISSUE TITLE
gather method should also return primary names

### ISSUE THREAD

**Issue by lwaldron** [vjcitn/MultiAssayExperiment#161]

**Comment by chapmandu2** [comment]
I think that it’s important to give the user the option of including in the extracted data frame additional information on samples and genes.  For example, if the primary key of the gene information in rowData is ensembl id, it would be convenient to easily be able to retrieve gene symbol instead/as well into the final data frame.  Otherwise you end up with a thee step process where you extract the data, join the gene info and join the sample info.  It is also really important that the gene primary keys are consistent between data types in the MultiAssayObject, I’m not sure how you achieve this.

**Comment by LiNk-NY** [comment]
I have added the `primary` column at 358a5ce3846f98f6f256fa1ad7706ab813324579
Will think about merging actual data to long and skinny DF
