### ISSUE TITLE
Revisit .checkMethods

### ISSUE THREAD

**Issue by mtmorgan** [vjcitn/MultiAssayExperiment#77]
https://github.com/vjcitn/biocMultiAssay/blob/renames/R/Elist-class.R#L55

avoid evaluation; discover in methods table. Relevance of Vince' report of changed methods table on package load (personal communication to mtmorgan).

**Comment by LiNk-NY** [comment]
@mtmorgan @lwaldron @vjcitn 

I created a .hasMethods function for checking that objects conform to API designated methods. It's a bit verbose as the hasMethod function sometimes requires two signatures rather than one depending on the function. 
I would appreciate your feedback on it. 
[https://github.com/vjcitn/biocMultiAssay/blob/renames/R/Elist-class.R#L2](https://github.com/vjcitn/biocMultiAssay/blob/renames/R/Elist-class.R#L2)

**Comment by LiNk-NY** [comment]
Avoid evaluation and rely on the `hasMethod` function. Current checks include "colnames", "rownames", "[", and "dim". See `.getMethErr` [in Elist-class.R](https://github.com/vjcitn/MultiAssayExperiment/blob/master/R/Elist-class.R#L97)
